# Generated by Django 6.0.3 on 2026-03-07 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=64)),
                ("nickname", models.CharField(default="Anonymous", max_length=50)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=64)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unique_views",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "unique_together": {("challenge", "session_key")},
            },
        ),
        migrations.CreateModel(
            name="DifficultyVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=64)),
                (
                    "difficulty",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Practice"),
                            (2, "Very Easy"),
                            (3, "Easy"),
                            (4, "Medium-Easy"),
                            (5, "Medium"),
                            (6, "Medium-Hard"),
                            (7, "Hard"),
                            (8, "Very Hard"),
                            (9, "Extreme"),
                            (10, "Impossible"),
                        ]
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_votes",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "unique_together": {("session_key", "challenge")},
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=64)),
                (
                    "stars",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "unique_together": {("session_key", "challenge")},
            },
        ),
        migrations.CreateModel(
            name="Solve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=64)),
                ("solved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solves",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "unique_together": {("session_key", "challenge")},
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("input_text", models.TextField(blank=True, null=True)),
                (
                    "input_file",
                    models.FileField(
                        blank=True, null=True, upload_to="challenge_inputs/"
                    ),
                ),
                ("output_text", models.TextField(blank=True, null=True)),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="challenge_outputs/"
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("challenge", "number")},
            },
        ),
    ]
