# Generated by Django 6.0.3 on 2026-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_off_topic",
            field=models.BooleanField(default=False),
        ),
    ]
