# Generated by Django 6.0.3 on 2026-04-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_comment_is_off_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="difficultyvote",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="rating",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
    ]
